app:
  name: 'hello-world'
  port: '1323'
log:
  env: 'dev'
  level: 'debug'

mysql:
  dbname: 'example_db'
  gormhost: '(127.0.0.1:3306)'
  max-idle-conns: 100
  max-open-conns: 100
  max-life-time-minutes: 5

secrets:
  mysql-sql-user: "root"
  mysql-sql-password: "password"